name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow --tags
        echo exit code $?
        git tag --list
        echo "APP_VERSION=$(git describe --tags --dirty=+)"

    - name: Get short git commit hash
      id: hash
      run: echo "::set-output name=hash::${GITHUB_SHA::7}"

    - name: Get version number
      id: version
      run: echo "::set-output name=version::$(git describe --tags --dirty=+)"

    - name: Get base hash
      id: base-hash
      run: echo "::set-output name=base-hash::$(sha512sum sample.asd | cut -b 1-8)"

    - name: Test if base exists
      id: base-exists
      run: echo "::set-output name=base-exists::$(podman manifest inspect quay.io/moxielogic/sample-base:${{ steps.base-hash.outputs.base-hash }} > /dev/null 2>&1 && echo 'EXISTS')"

    - name: Prepare base image
      id: build-base
      uses: redhat-actions/buildah-build@v2
      with:
        image: sample-base
        tags: ${{ steps.base-hash.outputs.base-hash }} latest
        dockerfiles: |
          build/Dockerfile.base
      if: ${{ steps.base-exists.outputs.base-exists != 'EXISTS' }}

    - name: Push Base To quay.io
      id: push-base-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-base.outputs.image }}
        tags: ${{ steps.build-base.outputs.tags }}
        registry: quay.io/moxielogic
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      if: ${{ steps.base-exists.outputs.base-exists != 'EXISTS' }}

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: sample
        tags: latest ${{ steps.hash.outputs.hash }} ${{ steps.version.outputs.version }}
        dockerfiles: |
          build/Dockerfile
        build-args: |
          APP_VERSION=${{ steps.version.outputs.version }}

    - name: Push to registry
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/moxielogic
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

    - name: Test
      run: |
        podman play kube test/test-pod.yml
        podman constainer sample-pod-sample
        ./test/test.sh $ip:8080 || true
        podman logs sample-pod-sample
